name: Elliott Hauser - since 1983
highlighter: rouge

title: Elliott Hauser
subtitle: doing stuff since 1983

sections:
  - bio

special-layouts:
  - "tools"

timezone: America/New_York

github: http://github.com/eah13
twitter: http://twitter.com/@hauspoor
linkedin: http://linkedin.com/in/elliotthauser
scholar: https://scholar.google.com/citations?user=OBskYc4AAAAJ&hl=en
academia: https://utexas.academia.edu/elliott
other_site: http://trinket.io

sass:
  implementation: sass-embedded
  style: expanded
  load_paths: ['bower_components/foundation/scss']
  
    
# Cloud9 settings
host: 0.0.0.0
port: 8080